### ISSUE TITLE
Config file documentation

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#155] opened 2021-02-25 12:27 UTC
Hi,

I was wondering if the new way configuration files are handled (in the develop branch following #114 and #117) is documented somewhere.
If not, and if I also want to avoid having a `climada` folder in my home, what are the steps to be taken? Would the following be enough?

1. Copy file `/path/to/climada_python/climada/conf/climada.conf` to `~/.config/climada.conf`.
2. Edit this newly create file `~/.config/climada.conf` for `local_data`.
3. To also edit the log level, edit `log_level` therein, too.

Would that be enough? Will this `~/.config/climada.conf` file always be used instead of `/path/to/climada_python/climada/conf/climada.conf`?

Also, upon moving that, should I also move the `~/climada` folder to where I point to in `local_data.system` and `local_data.demo` in `~/.config/climada.conf`? Or can I also just delete it and the required files will then be downloaded in the new folder automatically (which I would assume)?

If this is already documented somewhere, just pointing me to that should be enough.
Many thanks in advance!

**Comment by emanuel-schmid** [comment] 2021-03-05 12:41
Yes in theory, this is documented in the according [guide book](https://github.com/CLIMADA-project/climada_python/blob/develop/doc/guide/Guide_Configuration.ipynb) of the docs on develop branch.
At the very bottom of the notebook, a solution to your problem is described.

What you propose also works though. The file in `~/.config` will always be used. But not _instead_ of `/path/to/climada_python/climada/conf/climada.conf`; it is complementing and overwriting the latter.

You don't _have_ to move the `~/climada` folder but it's a good idea. Otherwise a new folder will be created at the configured location and some (but not all) files will be copied over.

**Comment by togeig** [comment] 2021-06-03 14:21
I recently upgraded to climada 2.1 and followed the recommendation by @emanuel-schmid according to the guide book. I simply copied the content of the config file over and changed the path to climada dir accordingly. But now when try to run a script I am confronted with a "JSONDecodeError: Expecting property name enclosed in double quotes." I am not a JSON expert but is there something wrong with the recommendation in the [guide book](https://github.com/CLIMADA-project/climada_python/blob/develop/doc/guide/Guide_Configuration.ipynb)? Any hint is appreciated. Thanks

**Comment by togeig** [comment] 2021-06-07 09:16
I solved my issue after fiddling around for some time. The issue is NOT related to the double quotes as indicated by the error. It's rather related to the trailing commas. If I remove both trailing commas that appear in the guide book recommendation, the issue is solved. Hope this helps anyone else in the future.

**Comment by emanuel-schmid** [comment] 2022-07-04 12:27
... one year later ...
fixed by 67d817b

**Closed by emanuel-schmid** 2022-07-04 12:27 UTC
Labels: question, conventions
