### ISSUE TITLE
Errors returned by hazard.plot_intensity()

### ISSUE THREAD

**Issue by sameberenz** [CLIMADA-project/climada_python#58] opened 2020-09-09 14:23 UTC
**Plotting hazard intensity returns a TypeError and a ValueError and no figure is displayed.**

The two errors are:
> TypeError: _pcolorargs() got an unexpected keyword argument 'allmatch'
> ValueError: Expected 2-dimensional array, got 1

**Below two examples with different hazard types.**

Are there any recent changes in [climada/util/plot.py](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/util/plot.py) (last changed by @tovogt), the [requirements](https://github.com/CLIMADA-project/climada_python/blob/develop/requirements/env_climada.yml) (last changed by @emanuel-schmid, @tovogt, and @mmyrte), or anywhere else that could have broken plot_intensity?

PS: plotting functions are unfortunately not thoroughly tested on jenkins currently.
PPS: I tagged it as "blocker" because the plotting functions are quite crucial for students, users, and developers; especially important to run and understand tutorials and check freshly initiated hazard sets.

**1. plotting crop hazard (relative_cropyield):** 

> 
> >> in[0]:

`hazard.plot_intensity(event=0)`
> >> out[0]:

```
~/Documents/Projects/climada_python/climada/util/plot.py:312: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  fig.tight_layout()
Traceback (most recent call last):

  File "<ipython-input-7-5c7ab9e6fd57>", line 1, in <module>
    haz1.plot_intensity(event=0)

  File "~/Documents/Projects/climada_python/climada/hazard/base.py", line 719, in plot_intensity
    smooth, axis, **kwargs)

  File "~/Documents/Projects/climada_python/climada/hazard/base.py", line 1134, in _event_plot
    l_title, smooth=smooth, axes=axis, **kwargs)

  File "~/Documents/Projects/climada_python/climada/util/plot.py", line 272, in geo_im_from_array
    axis.pcolormesh(grid_x, grid_y, np.squeeze(grid_im), transform=proj, **kwargs),

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1459, in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1491, in _pcolormesh_patched
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)

TypeError: _pcolorargs() got an unexpected keyword argument 'allmatch'

/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py:388: MatplotlibDeprecationWarning: 
The 'inframe' parameter of draw() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use Axes.redraw_in_frame() instead. If any parameter follows 'inframe', they should be passed as keyword, not positionally.
  inframe=inframe)
/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py:225: MatplotlibDeprecationWarning: Using a string of single character colors as a color sequence is deprecated since 3.2 and will be removed two minor releases later. Use an explicit list instead.
  **dict(style))
Traceback (most recent call last):

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 248, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 132, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/figure.py", line 1864, in draw
    renderer, self, artists, self.suppressComposite)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 388, in draw
    inframe=inframe)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2748, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py", line 228, in draw
    c.draw(renderer)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/collections.py", line 931, in draw
    Collection.draw(self, renderer)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/collections.py", line 412, in draw
    self._offset_position)

  File "/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 175, in draw_path_collection
    offset_position)

ValueError: Expected 2-dimensional array, got 1

<Figure size 648x936 with 2 Axes>
```

**2. TC hazard (witnessed by @simonameiler ):**

> >> in[0]:

`hazard_dict[‘Kerry_AL’].plot_intensity(event=i)`

> >> out[0]:

```
/Users/user/Documents/WCR/CLIMADA_develop/climada_python/climada/util/plot.py:314: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations.
  fig.tight_layout()
Traceback (most recent call last):

  File “<ipython-input-7-f64a17d65b5d>“, line 1, in <module>
    hazard_dict[‘Kerry_AL’].plot_intensity(event=hazard_dict[‘Kerry_AL’].event_id[impact_dict[‘Kerry_AL’].at_event == impact_dict[‘Kerry_AL’].at_event[idx]][0])

  File “/Users/user/Documents/WCR/CLIMADA_develop/climada_python/climada/hazard/base.py”, line 720, in plot_intensity
    smooth, axis, **kwargs)

  File “/Users/user/Documents/WCR/CLIMADA_develop/climada_python/climada/hazard/base.py”, line 1136, in _event_plot
    l_title, smooth=smooth, axes=axis, **kwargs)

  File “/Users/user/Documents/WCR/CLIMADA_develop/climada_python/climada/util/plot.py”, line 274, in geo_im_from_array
    transform=proj, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py”, line 1459, in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py”, line 1491, in _pcolormesh_patched
    X, Y, C = self._pcolorargs(‘pcolormesh’, *args, allmatch=allmatch)

TypeError: _pcolorargs() got an unexpected keyword argument ‘allmatch’

/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py:388: MatplotlibDeprecationWarning:
The ‘inframe’ parameter of draw() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use Axes.redraw_in_frame() instead. If any parameter follows ‘inframe’, they should be passed as keyword, not positionally.
  inframe=inframe)
/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py:225: MatplotlibDeprecationWarning: Using a string of single character colors as a color sequence is deprecated since 3.2 and will be removed two minor releases later. Use an explicit list instead.
  **dict(style))
Traceback (most recent call last):

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/formatters.py”, line 341, in __call__
    return printer(obj)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/pylabtools.py”, line 248, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, ‘png’, **kwargs))

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/IPython/core/pylabtools.py”, line 132, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backend_bases.py”, line 2217, in print_figure
    **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backend_bases.py”, line 1639, in wrapper
    return func(*args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py”, line 509, in print_png
    FigureCanvasAgg.draw(self)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py”, line 407, in draw
    self.figure.draw(self.renderer)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/figure.py”, line 1864, in draw
    renderer, self, artists, self.suppressComposite)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/image.py”, line 131, in _draw_list_compositing_images
    a.draw(renderer)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py”, line 388, in draw
    inframe=inframe)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py”, line 411, in wrapper
    return func(*inner_args, **inner_kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/axes/_base.py”, line 2748, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/image.py”, line 131, in _draw_list_compositing_images
    a.draw(renderer)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py”, line 228, in draw
    c.draw(renderer)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/collections.py”, line 931, in draw
    Collection.draw(self, renderer)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/artist.py”, line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/collections.py”, line 412, in draw
    self._offset_position)

  File “/Users/user/opt/anaconda3/envs/climada_env/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py”, line 175, in draw_path_collection
    offset_position)

ValueError: Expected 2-dimensional array, got 1

<Figure size 648x936 with 2 Axes>
```

**Comment by tovogt** [comment] 2020-09-09 14:29
Which version of matplotlib and cartopy do you use? (See https://github.com/SciTools/cartopy/issues/1615)

**Comment by sameberenz** [comment] 2020-09-09 14:47
As for your first question:

> cartopy                   0.17.0   
> matplotlib                3.1.0    

This is up to date with the [env_climada.yml](https://github.com/CLIMADA-project/climada_python/blob/develop/requirements/env_climada.yml )

**Comment by tovogt** [comment] 2020-09-09 15:16
I can't reproduce the error on the latest checkout of the develop branch. I even set up a fresh conda environment to make sure that I have exactly the packages listed in the requirements file.

I'm on Ubuntu 20.04. Are you on Windows or Mac? Did you try running everything in a clean conda environment?

**Comment by sameberenz** [comment] 2020-09-09 15:31
> I'm on Ubuntu 20.04. Are you on Windows or Mac? Did you try running everything in a clean conda environment?

Thanks for your effort!
I am working on macOS Mojave 10.14.6.
I have not tried a clean environment, yet.

**Comment by ChrisFairless** [comment] 2020-09-09 17:55
I tried to reproduce this on macOS Catalina 10.15.6 and couldn't
I found a different bug though (which is why I said it was failing earlier), so I'll open an issue for that :)

**Comment by simonameiler** [comment] 2020-09-10 06:04
I am working on mac OS Catalina 10.15.6
I just did a git pull and updated the conda environment:
conda env update --file requirements/env_climada.yml
conda env update --file requirements/env_developer.yml

The error persists.

**Comment by tovogt** [comment] 2020-09-10 06:46
@simonameiler @sameberenz Please do not just use the conda update function but create a new environment under a new name and try to reproduce the issue in that new environment. Conda often behaves strange when resolving dependencies.

**Comment by sameberenz** [comment] 2020-09-10 08:33
Deleting the environment `climada_env` and re-creating it following step 2 in the [CLIMADA installation guide](https://github.com/CLIMADA-project/climada_python/blob/develop/doc/guide/install.rst) resolved the issue.

@simonameiler @samluethi, this should also do the trick for you, otherwise please feel free to re-open this issue.

Thanks for your support, @tovogt !

**Comment by ChrisFairless** [comment] 2020-09-10 08:52
this would be a good thing for the future FAQ page

**Comment by tovogt** [comment] 2020-09-10 14:11
Would you please post the output of `import matplotlib; print(matplotlib.__version__)` in the same environment where you get the error message?

**Comment by tovogt** [comment] 2020-09-10 14:15
Okay, then you are not using the version of matplotlib in the requirements file. Does this version agree with the version specified in the output of `conda list` (executed in a shell within the same environment). With `print(matplotlib.__file__)` you can additionally check whether the path is actually in the conda environment you assume to be using.

**Comment by samluethi** [comment] 2020-09-10 14:23
so as output of conda list I get that matplotlib is 3.1.0 but matplotlib-base is 3.3.1
so somehow downgrading the matplotlib-base?

**Comment by tovogt** [comment] 2020-09-10 14:27
You can downgrade now, but that's not the interesting part. It's much more interesting how you arrived at that setup. You said that you re-installed the whole environment and you ended up with this mess. Can you please post the exact commands you use to setup a climada environment?

**Comment by samluethi** [comment] 2020-09-10 14:43
I've downgraded matplotlib-base to 3.2.1 - now it works (y)

For importing the environment I haven't used commands - I used the Import button in the anaconda navigator.

However, matplotlib-base is not specified in the requirements (only matplotlib). Maybe that's the issue?

**Comment by sameberenz** [comment] 2020-09-10 14:45
Probably - did you delete your `climada_env` environment in the anaconda-navigator (Environments > Remove) before importing it again from env_climada.yml?

**Comment by tovogt** [comment] 2020-09-10 14:47
Correct, the package "matplotlib-base" shouldn't be in a clean CLIMADA environment.

**Comment by samluethi** [comment] 2020-09-10 14:49
yes, I've removed it - I've even reinstalled anaconda. Thus, no idea how it's got there

**Comment by chahank** [comment] 2020-09-10 15:34
@tovogt In my climada_env there is also matplotlib-base. Not sure why it gets installed, but maybe it always comes togethe with matplotlib?

**Comment by tovogt** [comment] 2020-09-10 16:09
No, it doesn't always come together with matplotlib because otherwise it would be in a clean install of the CLIMADA environment. But you do have a point here:

1. We shouldn't require `matplotlib` at all since it's supposed to be used by end-users that manually install matplotlib. For their convenience, the package `matplotlib` comes bundled with pyqt. Instead, it is recommended (https://github.com/conda-forge/conda-forge.github.io/issues/933) to use `matplotlib-base` as a requirement.
2. There is no version `3.1.0` of `matplotlib-base`. That's why our dependency on `matplotlib` doesn't automatically install `matplotlib-base`. If, for example, we require `matplotlib=3.1.3` the package `matplotlib-base=3.1.3` will be automatically installed.
3. If a user installs any conda package that requires `matplotlib-base` conda will automatically install `matplotlib-base` in its latest available version and ignore the fact that `matplotlib` is already installed. That seems to be a pretty common scenario and my guess is that this also caused the confusion in this issue.

That's why I replaced the dependency `matplotlib=3.1.0` by `matplotlib-base=3.1.3` in 85134a1 which should fix this issue.

**Comment by sameberenz** [comment] 2020-09-11 08:31
I built a new clean conda environment with the updated requirements and plotting works fine. Thanks, Thomas!

N.B.: I noticed that in my new environment, now bot modules are installed, even though only matplotlib-base is in the requirements list:

```
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37h9aa3819_0 
```

**Comment by tovogt** [comment] 2020-09-11 08:34
Yes, I also noticed that both `matplotlib` and `matplotlib-base` are now included in the final environment. Probably some other package in our requirements file has a dependency on `matplotlib`. But that's okay I think.

**Closed by tovogt** 2020-09-11 08:34 UTC
Labels: blocker, bug
