### ISSUE TITLE
bug in read_ibtracs_netcdf

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#43] opened 2020-07-16 13:29 UTC
running:

tr_ibtracs = TCTracks()
tr_ibtracs.read_ibtracs_netcdf(provider='usa', correct_pres=True, year_range=(2002, 2007))

I get:

AttributeError: 'DataArray' object has no attribute 'str' 

at line 232 of tc_tracks.py:

232             years = ds.sid.str.slice(0, 4).astype(int)

it seems this bit of code was changed [here](https://github.com/CLIMADA-project/climada_python/commit/c4e6c17b9ca931977a1c4c2d7882b336cf91dea7#diff-47be3fff6f1949dcdcb92587af6cb05e)

**Comment by tovogt** [comment] 2020-07-16 14:07
Duplicate of https://github.com/CLIMADA-project/climada_python/issues/32, solution: update xarray to at least 0.13.0 (it's already in the requirements.yml). Sorry for the inconvenience!

**Closed by tovogt** 2020-07-16 14:07 UTC

**Comment by aleeciu** [comment] 2020-07-16 14:21
Thanks!
