### ISSUE TITLE
Incorrect centroids assignment in Exposures.assign_centroids()

### ISSUE THREAD

**Issue by ingajsa** [CLIMADA-project/climada_python#129] opened 2021-02-01 08:41 UTC
An incorrect centroid exposure assignment potentially occurs in Exposures.assign_centroids()  when hazard centroids and exposure coordinates do not perfectly match, in particular when the exposure is located at the same latitude as the hazard, but not at the same longitude.

The commands in line 210 - 213 do not correctly exclude exposures located outside the raster, but potentially assign them to other centroids within the raster.

As this function is a core CLIMADA - function I would recommend everyone to check whether the work is affected by this error. I will set up a fix branch for this very soon.

Cheers,

Inga

**Comment by chahank** [comment] 2021-02-01 08:50
Thanks for bringing this up!  Since this is a very core function of CLIMADA, we should proceed with care. Could you please give a detailed account of the problem here and discuss what you think is the solution?

**Comment by chahank** [comment] 2021-02-01 09:56
I suggests to take the occasion to have a more general discussion about what the `assign_centroids()` method should do and how it is thought  to be used. 

Let me start by noting two points:

- If the hazard centroids are a raster, should exposure points outside the raster be considered? (current default is no, but there is an error for points close to the raster as mentioned by Inga above)
- If the hazard centroids are points, how far away from the centroids should exposure points be considered? There is currently a `threshold` that can be set. However, when `impact.calc` is called, `assign_centroids` is called always with the default. Should the user be notified about this? Or can we expect a user to know this and apply `assign_centroids` manually before `impact.calc`?

**Comment by tovogt** [comment] 2021-02-01 10:12
@chahank There is actually a serious bug in the `assign_centroids` function. You are hijacking this issue to start a much broader discussion that will hamper a quick solution (hot fix) to the original bug this is about. I think that will be very harmful in the end.

**Comment by chahank** [comment] 2021-02-01 10:15
Fair enough. But please document clearly what the serious bug is. This is so far not clear at all.

**Comment by tovogt** [comment] 2021-02-01 10:29
Exposure points that lie outside of the hazard raster in longitudinal, but not in latitudinal directions, are assigned to completely wrong hazard raster points. I added unit tests (6e2b29e67f96a5dc3692d82dd6e1add0132abdc6) that reproduce this problem:
https://github.com/CLIMADA-project/climada_python/blob/6e2b29e67f96a5dc3692d82dd6e1add0132abdc6/climada/entity/exposures/test/test_base.py#L90-L129
Test results: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/feature%252Ffix_assign_centroids/1/testReport/junit/climada.entity.exposures.test.test_base/TestFuncs/test_assign_raster_pass/

**Comment by chahank** [comment] 2021-02-01 13:18
Solve with commit #130

**Closed** 2021-02-01 13:17 UTC
Labels: bug
