### ISSUE TITLE
get_country_code around antimeridian

### ISSUE THREAD

**Issue by ThomasRoosli** [CLIMADA-project/climada_python#770] opened 2023-08-15 09:38 UTC
Using get_country_code around the antimeridian can raise a ValueError unexpectedly.
The following code example is a simplified version of the locations of a Tropical Cyclone track around the antimeridian.
```
from climada.util.coordinates import get_country_code
lats = [45.201, 46.334, 47.988]
lons = [-179.902, -179.999, 180.002]
codes = get_country_code(lats, lons)
```
It raises a `ValueError: longitude extent range is greater than 360: -180.0 to 180.00300000000001 `
That happens because in get_country_code the extend is widened without any respect for the bounds of the projection
```
File ~/Documents/git_folder/climada_python/climada/util/coordinates.py:1544, in get_country_code(lat, lon, gridded)
   1542     extent = (lon.min() - 0.001, lon.max() + 0.001,
   1543               lat.min() - 0.001, lat.max() + 0.001)
```

**Comment by peanutfun** [comment] 2023-08-16 14:43
Are you certain that the coordinates you put in are correct? Why would they flip sign *and* cross the 180 degree limit?  `get_country_geometries` complains about the *absolute* range of the coordinates being greater than 360 degrees. It should handle the following case properly:
```python
from climada.util.coordinates import get_country_code
lats = [45.201, 46.334, 47.988]
lons = [-179.902, -179.999, -180.002]  # NOTE: All minus here!
codes = get_country_code(lats, lons)
```

**Comment by emanuel-schmid** [comment] 2023-09-13 09:23
As I see it, the problem is in the extent should never be calculated as `lon.min() - 0.001, lon.max() + 0.001` when it comes to longitude. Opposed to latitude, the points are not in an interval from -180 to +180 but on a _circle_ with coordinates where 179 is the same as -181. Instead of max and min as landmarks one should look for the biggest gap between the longitudinal coordinates.
![github](https://github.com/CLIMADA-project/climada_python/assets/51439563/c726475a-556b-41c8-9889-1a8ca2ed4d14)

**Comment by emanuel-schmid** [comment] 2023-09-13 11:03
I'll submit a pr with an implementation of that suggestion.

**Comment by peanutfun** [comment] 2023-09-13 13:27
@emanuel-schmid Isn't the same true for latitue as well? 🤔 The way I see it, the coordinates "just" have to be normalized, so either they go from 0 to 360 deg or from -180 to 180.

This normalization could happen automatically, but it need not: The check for the extent currently correctly captures the fact that the coordinates supplied by @ThomasRoosli "mix" these two types of limits.

**Comment by peanutfun** [comment] 2023-09-14 09:26
> This is not true for latitude where the distance is 180.

True, of course. It's only a half circle 🤦

@ThomasRoosli Could you please check if #785 resolves your original issue? Again, I want to stress that there seems to be an [inconsistency](https://github.com/CLIMADA-project/climada_python/issues/770#issuecomment-1680750566) in your coordinates, please check that again.

**Comment by emanuel-schmid** [comment] 2023-09-26 15:36
I've checked, #785 does resolve the original issue. closing this.

**Closed by emanuel-schmid** 2023-09-26 15:36 UTC
Labels: bug
